import { Manifest } from "../core/manifest";
import { EditorOverlay } from "../core/overlay";
import { extractTokenSettings, tokenToCodeMirrorClass } from "../core/schemas";

export function exportBrackets(manifest: Manifest, overlay: EditorOverlay): string {
  const lines: string[] = [];

  lines.push("/* Generated Brackets/CodeMirror Theme */");
  lines.push("/* DO NOT EDIT MANUALLY - Generated by Themebooth */");
  lines.push("");

  lines.push(".cm-s-themebooth {");

  lines.push("  background-color: " + (manifest.colors?.["editor.background"] || "#ffffff") + ";");
  lines.push("  color: " + (manifest.colors?.["editor.foreground"] || "#000000") + ";");

  lines.push("}");
  lines.push("");

  lines.push("/* Variables */");
  for (const [varName, value] of Object.entries(manifest.variables || {})) {
    lines.push(`@${varName}: ${value};`);
  }
  lines.push("");

  lines.push("/* Custom LESS Selectors */");
  for (const [selector, props] of Object.entries(overlay.less || {})) {
    lines.push(`.cm-s-themebooth ${selector} {`);
    for (const [prop, value] of Object.entries(props)) {
      lines.push(`  ${prop}: ${value};`);
    }
    lines.push("}");
  }
  lines.push("");

  lines.push("/* Token Styles */");
  for (const [scope, settings] of Object.entries(manifest.tokens || {})) {
    const extracted = extractTokenSettings(settings);
    if (Object.keys(extracted).length === 0) {
      continue;
    }

    const cmClass = tokenToCodeMirrorClass[scope] || scope;
    lines.push(`.cm-s-themebooth .${cmClass} {`);

    if (extracted.foreground) {
      lines.push(`  color: ${extracted.foreground};`);
    }
    if (extracted.background) {
      lines.push(`  background-color: ${extracted.background};`);
    }
    if (extracted.fontStyle) {
      lines.push(`  font-style: ${extracted.fontStyle};`);
    }
    if (extracted.fontWeight) {
      lines.push(`  font-weight: ${extracted.fontWeight};`);
    }
    if (extracted.opacity) {
      lines.push(`  opacity: ${extracted.opacity};`);
    }

    lines.push("}");
  }

  lines.push("");

  if (Object.keys(overlay.decorativeElements || {}).length > 0) {
    lines.push("/* Decorative Elements */");
    for (const [element, value] of Object.entries(overlay.decorativeElements || {})) {
      lines.push(`/* ${element}: ${value} */`);
    }
    lines.push("");
  }

  if (Object.keys(overlay.visualEffects || {}).length > 0) {
    lines.push("/* Visual Effects */");
    lines.push("/* Effects are documented but not all may be applicable to CodeMirror */");
    for (const [effect, value] of Object.entries(overlay.visualEffects || {})) {
      lines.push(`/* ${effect}: ${JSON.stringify(value)} */`);
    }
  }

  return lines.join("\n");
}
