import { Manifest } from "../core/manifest";
import { EditorOverlay } from "../core/overlay";
import { mergeTokenOverrides } from "./utils";

export interface VimColorScheme {
  name: string;
  background: string;
  foreground: string;
  highlights: Record<string, VimHighlight>;
}

export interface VimHighlight {
  ctermbg?: string;
  ctermfg?: string;
  guibg?: string;
  guifg?: string;
  cterm?: string;
  gui?: string;
}

export function exportVim(manifest: Manifest, overlay: EditorOverlay): string {
  const lines: string[] = [];

  lines.push(`" Generated Vim Color Scheme`);
  lines.push(`" Theme: ${manifest.name}`);
  lines.push(`" Author: ${manifest.author}`);
  lines.push(`" DO NOT EDIT MANUALLY - Generated by Themebooth`);
  lines.push("");

  lines.push(`set background=dark`);
  lines.push(`hi clear`);
  lines.push(`if exists("syntax_on")`);
  lines.push(`  syntax reset`);
  lines.push(`endif`);
  lines.push("");

  lines.push(`let colors_name = "${manifest.name}"`);
  lines.push("");

  // Extract basic colors
  const bgColor = manifest.colors?.["editor.background"] || "#1e1e1e";
  const fgColor = manifest.colors?.["editor.foreground"] || "#d4d4d4";

  lines.push(`" Editor Colors`);
  lines.push(`hi Normal guibg=${bgColor} guifg=${fgColor}`);
  lines.push("");

  // Add token highlights from manifest
  const manifestTokens = mergeTokenOverrides(manifest, null);
  if (manifestTokens.length > 0) {
    lines.push(`" Token Colors`);
    for (const rule of manifestTokens) {
      const vimScope = vimTokenMap[rule.scope] || rule.scope;
      const highlight = buildVimHighlight(rule.settings);
      lines.push(`hi ${vimScope} ${highlight}`);
    }
  }

  // Add overlay overrides if any
  if (overlay?.tokenOverrides && Object.keys(overlay.tokenOverrides).length > 0) {
    lines.push("");
    lines.push(`" Token Overrides`);
    const merged = mergeTokenOverrides(manifest, overlay);
    const overlayOnlyTokens = merged.filter((t) => overlay.tokenOverrides?.[t.scope]);

    for (const rule of overlayOnlyTokens) {
      const vimScope = vimTokenMap[rule.scope] || rule.scope;
      const highlight = buildVimHighlight(rule.settings);
      lines.push(`hi ${vimScope} ${highlight}`);
    }
  }

  return lines.join("\n");
}

const vimTokenMap: Record<string, string> = {
  comment: "Comment",
  keyword: "Keyword",
  string: "String",
  number: "Number",
  constant: "Constant",
  builtin: "Type",
  variable: "Identifier",
  function: "Function",
  operator: "Operator",
  punctuation: "Delimiter",
  tag: "Tag",
  attribute: "Attribute",
  entity: "Structure",
  invalid: "Error",
};

function buildVimHighlight(settings: Record<string, any>): string {
  const parts: string[] = [];

  if (settings.foreground) {
    parts.push(`guifg=${settings.foreground}`);
  }

  if (settings.background) {
    parts.push(`guibg=${settings.background}`);
  }

  if (settings.fontStyle) {
    const style = settings.fontStyle.toLowerCase();
    const vimStyle: string[] = [];

    if (style.includes("bold")) vimStyle.push("bold");
    if (style.includes("italic")) vimStyle.push("italic");
    if (style.includes("underline")) vimStyle.push("underline");

    if (vimStyle.length > 0) {
      parts.push(`gui=${vimStyle.join(",")}`);
    }
  }

  return parts.join(" ");
}
